### ISSUE TITLE
在asp.net mvc 项目中安装这个包报错 

### ISSUE THREAD

**Issue by smilexlong** [CBDlkl/AspnetCoreApiDoc#1]
无法安装程序包“AspnetCoreApiDoc 3.0.1”。你正在尝试将此程序包安装到目标为“.NETFramework,Version=v4.5”的项目中，但该程序包不包含任何与该框架兼容的程序集引用或内容文件。有关详细信息，请联系程序包作者。

**Comment by li-keli** [comment]
抱歉，这个项目包仅支持 `NetCore2.0+` 平台，并不完全兼容`NETFramework `

**Comment by ZYQiang** [comment]
我这边netcore5.0 项目，引用包后没有反应 get /core/v1/api.do file do ext not support

**Comment by ZYQiang** [comment]
![1636338094(1)](https://user-images.githubusercontent.com/21325933/140674491-0b9c27c5-c154-4530-bb8e-8b38da3bfd0d.png)
接口报错

**Comment by kensmaster** [comment]
请问前端如何调用呀 有没有demo

**Comment by li-keli** [comment]
> 我这边netcore5.0 项目，引用包后没有反应 get /core/v1/api.do file do ext not support

netcore高版本还未支持，有些API变化大，提供一下错误的堆栈信息

**Comment by ZYQiang** [comment]
> > 我这篇netcore5.0项目，引用包后没有反应 get /core/v1/api.do file do ext not support
> 
> netcore高版本不支持，每次API变化大，提供一次错误的信息
![1637038142(1)](https://user-images.githubusercontent.com/21325933/141922938-83151314-ecb4-400c-849a-fe4753e11993.png)

我这边没有用Dto，直接定义的基本类型参数

**Comment by ZYQiang** [comment]
> 前端如何调用呀有没有demo
http://localhost:xxxx/core/v1/api.do

**Comment by li-keli** [comment]
https://github.com/li-keli/AspnetCoreApiDoc/issues/6
参考一下这个iss
