### ISSUE TITLE
请问前端如何调用呀 有没有demo

### ISSUE THREAD

**Issue by kensmaster** [CBDlkl/AspnetCoreApiDoc#6]
请问前端如何调用呀 有没有demo

**Comment by li-keli** [comment]
![image](https://user-images.githubusercontent.com/9330061/141445880-efe850a8-ca51-4a5e-a9eb-157d001cbea1.png)

在生成的文档上面有POST请求地址

**Comment by kensmaster** [comment]
> ![image](https://user-images.githubusercontent.com/9330061/141445880-efe850a8-ca51-4a5e-a9eb-157d001cbea1.png)
> 
> 在生成的文档上面有POST请求地址

谢谢，不打算使用这个了，只支持protoBuf
